// Auto-generated by scripts/build-dashboard.py
window.TOPIC_RADAR_DATA = {
  "generated_at": "2026-05-22T06:59:12.204889Z",
  "days": [
    {
      "date": "2026-05-21",
      "file": "outputs/daily/2026-05-21-topic-radar.md",
      "top_topics": [
        {
          "title": "1) SpaceX IPO 文件曝光：AI 算力“超级甲方”出现了——Anthropic 月付 $12.5 亿买算力",
          "score_total": 29,
          "sources": [
            "Axios（2026-05-21）：https://www.axios.com/2026/05/21/ai-news-cycle-openai-anthropic-spacex",
            "DCD / DataCenterDynamics（2026-05-21，转述 IPO 文件披露细节，写作时需回到原文件或多方交叉核实）：https://www.datacenterdynamics.com/en/news/spacex-ipo-filing-reveals-anthropic-set-to-pay-musks-firm-125bn-a-month-to-rent-xai-data-center-space/",
            "Reuters（无法直接访问原文时，可用同日转引作线索，但事实点以 SpaceX 公开文件/多方交叉核实为准，且需标注“需要二次核实”）"
          ],
          "summary": "SpaceX 的 IPO 文件把 AI 业务赌注摊牌：不仅做火箭/卫星，还把“AI 训练基础设施”当成未来增长引擎。 同一份披露里最炸裂的细节：Anthropic 扩大与 SpaceX 相关算力合作，公开报道披露其支出规模约 $1.25B/月（写作时要强调：金额口径与合同条款需二次核实）。",
          "why_it_matters": "你在校准备的“AI / SWE / Infra”不只是大厂/创业公司路线：AI 时代的高薪岗位正在往“算力—数据中心—训练平台—可靠性工程”集中，而“谁敢长期签下天价算力合同”本质是行业景气度与用人强度的信号。 IPO 披露把很多“只在圈内聊”的信息变成了公开材料：对你判断 哪些方向更缺人、哪些技能更值钱 更有依据。",
          "job_signal": "1. AI Infra / Data Center / Distributed Systems 的“现金流可解释性”变强：月付级别的长期算力合同→行业里真实存在“能消化算力”的产品需求与付费能力（但具体合同条款需二次核实）。 2. Cloud/Compute 版图出现新对手：除了传统云厂商，“算力供给侧”也可能出现新的强势玩家→对应机会更偏工程化与硬核基建（网络、集群调度、存储、GPU/加速器、能源）。 3. IPO=招聘叙事窗口：巨型 IPO 前后通常伴随“对外叙事、组织扩张、合规与财务体系强化”→不仅是 SWE/ML，也会拉动 Security、Compliance、Finance、IR、Internal Tools。"
        },
        {
          "title": "2) 白宫临时叫停/推迟 AI 行政令：AI 安全与监管“要加速但很难拍板”——对求职意味着什么？",
          "score_total": 26,
          "sources": [
            "AP（2026-05-21）：https://apnews.com/article/ee318f35acc8a2c43e47f3ebf26cb459",
            "Axios（2026-05-21，多角度补充）：",
            "https://www.axios.com/2026/05/21/trump-ai-executive-order-postponed-why",
            "https://www.axios.com/2026/05/21/white-house-postpones-ai-eo-signing",
            "Reuters（经 Investing/TradingView 转引，2026-05-21）：",
            "https://www.investing.com/news/stock-market-news/trump-to-sign-order-on-ai-oversight-as-security-fears-mount-among-supporters-4702720",
            "https://www.tradingview.com/news/reuters.com%2C2026%3Anewsml_L6N41X17M%3A0-trump-to-sign-order-on-ai-oversight-as-security-fears-mount-among-supporters/"
          ],
          "summary": "原计划在 2026-05-21 签署的 AI 与网络安全相关行政令/框架出现临时变动（推迟/叫停），公开报道给出的原因包括：担心影响美国 AI 竞争力，以及来自不同阵营的安全与监管压力。 关键信号不是“今天到底签没签”，而是：政府层面确实在推动对最先进 AI 的安全审查与治理框架，但推进路径存在拉扯。",
          "why_it_matters": "未来 6-18 个月，AI 行业的“增量岗位”不只在模型训练：还会在 AI 安全、合规、评测、红队、隐私、供应链安全 等方向出现结构性需求。 留学生在择业上会遇到现实约束：一些敏感领域可能涉及身份/背景审查；理解政策走向有助于你 避坑 + 选方向（必须提示：具体限制以公司与岗位要求为准）。",
          "job_signal": "1. AI Security/AI Governance 变成“可被预算化”的工作：当政策/框架进入拟定期，企业会提前布局安全评测与合规流程→对应岗位更像“工程 + 政策 + 风控”的交叉。 2. 网络安全与 AI 绑定更紧：行政令讨论中把 AI 与 cyber 放一起→安全岗位的技能栈正在向“模型评测/对抗/供应链”扩展。 3. 对留学生最现实的启发：如果你拿不到最核心的模型训练团队机会，可以把目标切到“AI 系统上线前后的安全与可靠性”。"
        },
        {
          "title": "3) 美国商务部拟向 9 家量子公司发出 $20 亿“意向书”（含股权/可转债）：量子赛道的招聘与移民路径怎么押？",
          "score_total": 23,
          "sources": [
            "NIST/美国商务部公告（2026-05-21）：https://www.nist.gov/news-events/news/2026/05/department-commerce-announces-letters-intent-9-companies-2-billion",
            "Reuters（经 WSJ/其他媒体转引的同日讨论可作传播辅助，但事实点以官方公告为准）"
          ],
          "summary": "美国商务部宣布将向 9 家量子信息科技公司发出“资金支持意向书（Letters of Intent）”，总额最高 $2B；并明确提到可能采用 股权、可转换债等工具（属于非常强的产业政策信号）。",
          "why_it_matters": "量子不是“离你太远的科研新闻”，它更像是下一阶段的“高端人才争夺战”：一旦联邦资金与产业链成形，对应的 硬件、系统软件、芯片、算法、编译、低温工程、验证测试 都会需要人。 对留学生来说，这类赛道的优势是：更看重硬技能与研究/工程能力；劣势是：可能更敏感、更挑背景与合规要求（必须提醒个案差异）。",
          "job_signal": "1. 资金工具升级=产业化意图强：从 grant 到股权/可转债→更像“把公司做大做强”的打法→更可能扩招工程与产品化岗位（但扩招规模需二次核实）。 2. 跨学科岗位会冒出来：量子 + HPC + 云 + 安全→对 CS/EE/物理交叉背景更友好。 3. 对普通 CS 留学生的机会点：不一定要“会量子物理”，可以从 编译器/系统/分布式/HPC/性能工程 切入。"
        }
      ],
      "alternatives": [
        {
          "title": "SpaceX“CEO for life/超高投票权”治理结构",
          "summary": "用 IPO 治理条款给投行/咨询/PE/VC 方向做面试表达训练（Axios，2026-05-21）。https://www.axios.com/2026/05/21/musk-ceo-spacex-control",
          "score_total": 20
        },
        {
          "title": "“两小时改变 AI 新闻周期”",
          "summary": "把 Anthropic 财务 + SpaceX 算力 + 政策拉扯串成“岗位结构变化”推演框架（Axios，2026-05-21）。https://www.axios.com/2026/05/21/ai-news-cycle-openai-anthropic-spacex",
          "score_total": 21
        },
        {
          "title": "SpaceX 级别 IPO 的外溢：ECM/IPO 项目密度怎么影响校招",
          "summary": "从“项目储备—团队负荷—新人机会”写投行判断（Reuters 转引，2026-05-21，事实以正式文件为准）。https://uk.marketscreener.com/news/bound-for-mars-elon-musk-s-spacex-unveils-filing-for-blockbuster-ipo-ce7f5ad9df8ff022",
          "score_total": 19
        },
        {
          "title": "AI 编程热潮引发生产事故讨论",
          "summary": "用“AI coding + 可靠性/SRE”做岗位切入（VentureBeat，2026-05-21）。https://venturebeat.com/technology/resolve-ai-says-the-ai-coding-boom-is-breaking-production-systems-it-wants-to-fix-that/",
          "score_total": 20
        },
        {
          "title": "SpaceX IPO 外溢效应：欧洲航天股走强",
          "summary": "适合做“航天/卫星/通信产业链岗位地图”（Reuters 转引，2026-05-21）。https://www.stocktitan.net/news/RL/spacex-ipo-filing-lifts-european-space-stocks-jkl4xo43mt1c.html",
          "score_total": 18
        },
        {
          "title": "AI 安全与竞争力的公开冲突",
          "summary": "做“AI Safety/治理岗位为何会变热”的二创解读（AP，2026-05-21）。https://apnews.com/article/ee318f35acc8a2c43e47f3ebf26cb459",
          "score_total": 19
        },
        {
          "title": "社区热帖（仅作辅助素材）",
          "summary": "r/technology 对 SpaceX IPO 与算力大单的高互动讨论，用来提炼读者疑问，但事实必须回到权威来源二次核实（Reddit，2026-05-21）。https://www.reddit.com/r/technology/comments/1tj5hbq/spacex_ipo_filing_lays_bare_losses_and_musk/",
          "score_total": 16
        }
      ]
    },
    {
      "date": "2026-05-20",
      "file": "outputs/daily/2026-05-20-topic-radar.md",
      "top_topics": [
        {
          "title": "选题 A｜Nvidia 业绩 + $80B 回购：AI infra 的“就业温度计”还在升温",
          "score_total": 28,
          "sources": [
            "Reuters（转载：Investing.com）：Nvidia forecasts Q2 revenue above estimates, announces $80 billion buyback",
            "TechCrunch：Nvidia earnings show big boost from AI, but China restrictions loom",
            "Reddit（高互动，辅助观察）：r/wallstreetbets “NVDA EARNINGS THREAD …” / r/NVDA_Stock"
          ],
          "summary": "Nvidia 发布最新季度业绩与指引，并宣布新的 $80B 股票回购授权；媒体解读核心仍是 AI 需求强劲，但也提到中国限制带来的不确定性（背景资料：限制并非当日新推出）。",
          "why_it_matters": "Nvidia 的指引与资本开支链条，往往是“云厂/数据中心/AI infra”招聘景气度的领先指标：只要需求继续上修，相关岗位（云、分布式系统、推理优化、GPU 软件栈、数据中心运维/供应链）更可能出现新增 headcount。 对尚未毕业的学生而言，这类信号能帮助你决定：该把项目/实习经历压在哪条“AI 基建主线”上，而不是只追逐泛 AI 标签。",
          "job_signal": "“需求继续强、公司愿意用资本回购 + 给出高指引” → 行业信心仍在：更利好 AI infra/平台工程/性能工程/芯片生态 方向的实习与 NG。 风险侧信号：提到中国限制 → 地缘/合规 会影响产品线与团队资源分配，岗位策略要更“可迁移”（见风险提示）。"
        },
        {
          "title": "选题 B｜量化基金把 GPU 云“买到位”：Lambda × Hudson River Trading 的 AI/算力合作",
          "score_total": 28,
          "sources": [
            "Lambda 官方博客：Lambda and Hudson River Trading build new relationship for AI compute",
            "Reuters（转载：Investing.com）：Nvidia quarterly results …（文内提及该合作）",
            "Reddit（辅助观察）：r/quant “Ken Griffin … AI Research” 等当日讨论贴（仅作情绪/关注度参考）"
          ],
          "summary": "AI/GPU 云厂商 Lambda 宣布与 Hudson River Trading（HRT） 建立新的合作关系，为其提供 AI 计算资源（细节以原文为准）。",
          "why_it_matters": "量化/HFT 的“机会信号”不一定来自公开招聘，而常来自：算力采购、研究基础设施升级、与云/硬件供应商绑定。这往往意味着： 研究团队正在扩容/提效（更需要 ML/系统/数据/平台工程） 或者交易/研究方法在向 AI 进一步渗透（更需要能落地的工程化能力）",
          "job_signal": "“买算力=买产能”：对学生来说，是一个把简历从“刷题选手”升级为“研究/工程能交付”的提示——你需要能讲清楚：你如何把模型/策略跑起来、压成本、提吞吐、控延迟、做可观测。 量化与 GPU 云绑定 → 更利好以下方向：`ML Infra / Data Engineering / Distributed Systems / GPU performance / Research Engineer`。"
        },
        {
          "title": "选题 C｜投行自己要 IPO：Lincoln International 上市首日大涨，资本市场窗口在变",
          "score_total": 26,
          "sources": [
            "Reuters（转载：Investing.com）：Investment bank Lincoln International shares jump in market debut"
          ],
          "summary": "投资银行 Lincoln International IPO 上市首日股价上涨（具体涨幅以报道为准），释放出：资本市场窗口/投资银行业务的景气度可能在改善。",
          "why_it_matters": "对投行/资本市场相关求职者，IPO 成功与否直接影响： ECM/IB 的 deal flow 预期（从而影响 internship / analyst headcount 与 return offer） 市场对“投行行业复苏”的共识强弱（影响择业与准备节奏）",
          "job_signal": "“投行 IPO 受追捧”是一种行业情绪信号：若后续更多发行推进，IB/ECM/资本市场相关岗位的机会可能更稳定。 对学生的可执行动作：把准备从“泛泛投行八股”升级为“今年市场真正发生的 deal 类型”（industrial, tech, energy, sponsor-backed 等），以及对应 pitch/建模案例。"
        }
      ],
      "alternatives": [
        {
          "title": "Intuit 宣布裁员约 17%（Reuters/TechCrunch）",
          "summary": "适合写“AI 转型期的避坑与转岗策略”，但不建议写成“行业崩了”。",
          "score_total": 21
        },
        {
          "title": "NextEra Energy Partners 收购天然气管道公司 Caliber（Reuters）",
          "summary": "数据中心/发电/燃气基础设施与 AI 扩张绑定，适合写“AI 数据中心=电力与管网岗位机会”。",
          "score_total": 22
        },
        {
          "title": "HSBC CEO 谈 AI 会摧毁也会创造岗位、强调再培训（Reuters）",
          "summary": "可写“金融业 AI 化下的新岗位画像（风控/数据/平台）”，但需要补充更多一手招聘证据（LinkedIn 需二次核实）。",
          "score_total": 20
        },
        {
          "title": "Hazeltree 披露 4 月 hedge funds 加杠杆、调整对冲（Reuters）",
          "summary": "可写“波动期对冲基金在招什么（风险/系统/执行）”，但信号偏宏观，需要强包装。",
          "score_total": 18
        },
        {
          "title": "“美股期货上涨，市场等待 Nvidia 财报”（Reuters）",
          "summary": "可作为选题 A 的导语或数据点，不建议单独成稿。",
          "score_total": 15
        },
        {
          "title": "Reddit：Intuit layoff 高互动讨论贴（r/technology 等）",
          "summary": "可作为“员工视角”素材补充，但需避免把社区观点当事实。",
          "score_total": 16
        },
        {
          "title": "Reddit：Nvidia earnings thread 高互动讨论（r/wallstreetbets / r/NVDA_Stock）",
          "summary": "适合作为“情绪温度计”和读者互动引导（投票/提问），不宜替代权威来源。",
          "score_total": 17
        }
      ]
    },
    {
      "date": "2026-05-19",
      "file": "outputs/daily/2026-05-19-topic-radar.md",
      "top_topics": [
        {
          "title": "选题 1：Google × Blackstone 造“独立 TPU 云公司”——AI Infra 从“技术战”变“资本战”，对留学生意味着什么？",
          "score_total": 27,
          "sources": [
            "Yahoo Finance（转述公司声明/报道）：[Google and Blackstone to launch AI cloud venture backed by $5 billion](https://finance.yahoo.com/sectors/technology/articles/google-blackstone-launch-ai-cloud-104518486.html)",
            "Investing.com（转述 WSJ/公司信息）：[Google, Blackstone plan new AI cloud company with $5 bln investment](https://uk.investing.com/news/stock-market-news/google-blackstone-plan-new-ai-cloud-company-wsj-4686555)",
            "Network World（行业解读）：[Google opens TPUs to enterprises beyond its own cloud via Blackstone JV](https://www.networkworld.com/article/4173075/google-opens-tpus-to-enterprises-beyond-its-own-cloud-via-blackstone-jv.html)"
          ],
          "summary": "Google 与 Blackstone 宣布成立 AI 云业务合资公司/新公司，核心卖点是 基于 Google TPU 的算力服务。 公开信息提到 Blackstone 先投 约 50 亿美元股权，目标在 2027 年带来约 500MW 计算/数据中心容量，并计划继续扩张。（需要二次核实：最终结构、容量口径、所在地与交付节奏）",
          "why_it_matters": "你可以把它理解为：AI 竞争的“瓶颈”正在从模型能力，转到算力、机房、电力、网络与资本结构。这会改变未来 1-2 年的招聘重心：更偏 AI infra / cloud / systems / data center / 网络 / 电力与散热，以及“懂技术的金融/战略/BD”岗位。 对尚未毕业的学生尤其关键：大厂/巨头更愿意把预算砸在 CapEx 和 infra 上，但同时会更苛刻地要求“能落地、能节省成本、能上生产”的能力组合。",
          "job_signal": ""
        },
        {
          "title": "选题 2：Meta 5/20 启动新一轮裁员+“AI Pod 化”改组织——你该怎么把自己写成“不会被 AI 取代的那类新人”？",
          "score_total": 27,
          "sources": [
            "IT Pro（引用 Reuters 看到的内部 memo）：[Internal memo suggests Meta will lay off 10%...](https://www.itpro.com/business/leadership/internal-memo-suggests-meta-will-lay-off-10-percent-of-its-employees-with-a-further-10-percent-set-to-be-transferred-to-better-focus-on-ai)",
            "The Economic Times（转述 Reuters，含“关闭 6000 个开放岗位”等细节）：[Meta lays out plans for May 20 layoffs...](https://economictimes.indiatimes.com/tech/technology/meta-lays-out-plans-for-may-20-layoffs-restructuring-internal-document-says/articleshow/131185217.cms)",
            "背景资料（2026-05-18 Reuters 原文转载）：[Exclusive-Meta lays out details...](https://m.investing.com/news/stock-market-news/exclusivemeta-lays-out-plans-for-may-20-layoffs-restructuring-internal-document-says-4696710?ampMode=1)"
          ],
          "summary": "多家媒体在 5/19 转述：Meta 计划在 5/20 进行约 10% 裁员，并伴随更大范围的组织调整，强调“围绕 AI workflow/AI agent 重新设计组织”，把部分员工转去 AI 相关新项目、压扁管理层、并披露 关闭一批 open roles（报道提到 6000）。（需要二次核实：最终裁员比例、涉及团队、open roles 口径）",
          "why_it_matters": "“大厂裁员”本身不是新闻点，真正对学生有用的是：大厂正在把‘工作流’变成 AI 可自动化的对象。 这会直接改变 entry-level 的竞争方式：你不仅要会写代码/做分析，更要能证明你能 搭建系统、驱动指标、把 AI 工具嵌入流程并产出稳定结果。 同时也提示求职风险：offer → headcount 冻结/关闭 open role 的概率上升，学生必须把“备选公司与身份路径”放进策略里。",
          "job_signal": "“AI for Work”相关：内部工具平台、Agent/Workflow、数据治理、评估与监控（eval/observability）、安全合规（尤其是企业场景）。 对新人更友好的突破口：Platform/SRE/数据平台/生产工程，因为这是“让 AI 真上生产”的底座。 风险侧信号：open roles 关闭 → 说明“HC 与招聘节奏”高度不稳定（尤其非核心团队）。"
        },
        {
          "title": "选题 3：AI 数据中心“模块化工厂化”加速——Armada 融资 2.3 亿美元、在亚利桑那建厂（直说：这类公司更可能给新人机会）",
          "score_total": 27,
          "sources": [
            "PRNewswire/StreetInsider：[Armada Raises $230M... plans modular data center factory in Arizona](https://www.streetinsider.com/PRNewswire/Armada%2BAnnounces%2BAgreement%2Bwith%2BJohnson%2BControls%2Bfor%2BGalleon%2BForge%2BOne%3B%2BRaises%2B%24230M%2Bin%2BOversubscribed%2BSeries%2BB%2Bwith%2Ba%2BPre-Money%2BValuation%2Bof%2B%242B%2Bto%2BAccelerate%2BDeployment%2Bof%2Bthe%2BU.S.%2BAI%2BStack%2Band%2BSupp/26516211.html)",
            "Investing.com（转述公司声明，含“500 jobs”等数字）：[Armada capta US$ 230 milhões... fábrica no Arizona](https://br.investing.com/news/company-news/armada-capta-us-230-milhoes-em-rodada-de-financiamento-serie-b-93CH-1944210)"
          ],
          "summary": "Armada 宣布 超额认购的 B 轮融资 2.3 亿美元（披露估值口径为 pre-money 20 亿美元），并与 Johnson Controls 达成框架协议，计划在 亚利桑那建设模块化数据中心生产工厂。 报道提到该工厂项目预计带来 约 500 个直接岗位，以及供应链带动岗位。（需要二次核实：岗位结构、招聘节奏、是否面向应届/实习）",
          "why_it_matters": "对学生而言，这类“AI 基建供应链公司/数据中心产业链公司”往往比巨头更可能给新人 更快的 ownership 与更明确的业务增长叙事（融资 + 建厂 + 交付）。 同时它把“AI infra”从纯软件拉回到“软硬结合”：电力、制冷、机械、可靠性、供应链、工厂运营——非传统 CS 背景也可能切入。",
          "job_signal": ""
        }
      ],
      "alternatives": []
    }
  ]
};
