// Auto-generated by scripts/build-dashboard.py
window.TOPIC_RADAR_DATA = {
  "generated_at": "2026-06-08T08:17:23.301352Z",
  "days": [
    {
      "date": "2026-06-07",
      "file": "outputs/daily/2026-06-07-topic-radar.md",
      "top_topics": [
        {
          "title": "1. OpenAI 想把 ChatGPT 做成超级入口：AI 产品、Agent 和搜索方向值得继续跟",
          "score_total": 28,
          "sources": [
            "Reuters，2026-06-07",
            "Financial Times，2026-06-07"
          ],
          "source_urls": [
            "https://finance.yahoo.com/news/openai-plans-chatgpt-superapp-overhaul-213458523.html",
            "https://www.ft.com/"
          ],
          "summary": "Reuters 6 月 7 日援引 Financial Times 报道称，OpenAI 正在推进 ChatGPT 的 superapp 改造，方向包括个性化、购物、支付、搜索和用户自建 agent / app 生态。 目前能确认的是产品方向在继续外扩，ChatGPT 想做更大的用户入口。 当天没有公开信息证明会立刻带来大规模扩招。",
          "why_it_matters": "这条新闻说明，AI 求职重点还会继续往产品、平台和 agent 应用走。 对学生来说，光会调 API 已经不够，最好能证明你理解用户入口、任务流程和产品闭环。 如果你原本只准备通用 SWE 面试，这条线索提醒你要更早补 AI 产品理解和 agent 项目。",
          "job_signal": "可核实事实：OpenAI 被曝考虑把 ChatGPT 做成更完整的平台型产品。 可写方向：AI Product、Applied AI、Agent Engineering、Search / Recommendation、Growth PM、Full-stack。 这说明整个 AI 应用层都在抢入口和用户时长。"
        },
        {
          "title": "2. 华尔街开始公开谈 AI 压缩初级岗：金融求职门槛在提高",
          "score_total": 29,
          "sources": [
            "Fortune，2026-06-07"
          ],
          "source_urls": [
            "https://fortune.com/2026/06/07/banks-mass-workforce-cuts-ai-entry-level-jobs-junior-analysts/"
          ],
          "summary": "Fortune 6 月 7 日汇总多家大行高管表态，称 AI 正在提升效率，也会压缩一部分初级岗位工作量。 受影响最大的，是文档整理、基础分析、重复写作和执行类工作。 可核实事实是，银行高层已经开始公开谈 AI 对 junior work 的替代。",
          "why_it_matters": "对还没毕业的学生来说，最直接的变化是初级岗位竞争会更激烈。 会用 AI 做研究、自动化和信息整理的人，会更容易拉开差距。 对投行、销售交易、研究、风控这些方向来说，门槛在提高。",
          "job_signal": "可核实事实：华尔街高层正把 AI 替代部分初级工作的影响公开化。 可写方向：research automation、dashboard、数据清洗、行业资料整理、AI + finance 复合能力。 文章重点放在什么能力更值钱。"
        },
        {
          "title": "3. 数据中心争议升温：AI 基建、能源和数据中心岗位值得关注",
          "score_total": 26,
          "sources": [
            "The Washington Post，2026-06-07"
          ],
          "source_urls": [
            "https://www.washingtonpost.com/politics/2026/06/07/ai-backlash-coming-key-midterm-battlegrounds/"
          ],
          "summary": "Washington Post 6 月 7 日报道，美国多地围绕数据中心、电力、水资源和社区影响的争议正在升温。 相关议题已经进入地方政治讨论。 当天能确认的是，数据中心扩张面临更多约束，但还没有出现全面叫停。",
          "why_it_matters": "这条新闻提醒大家，AI 机会也在模型之外的基建环节。 真正长期花钱的环节还包括数据中心、云、网络、电力和冷却。 对想找更稳岗位的学生，这些方向值得更早了解。",
          "job_signal": "可核实事实：地方层面的数据中心反弹在上升，但没有形成全面封锁。 可写方向：cloud infra、data center operations、network engineering、power systems、sustainability、site selection、supply chain。 预算会继续流向基建、运维和容量相关岗位，这类方向更适合做中长期布局。"
        }
      ],
      "alternatives": [
        {
          "title": "AI mega stock deals raise specter of more shares than buyers",
          "summary": "AI 龙头继续吸走市场资金，IPO 和一级市场热度还会在。适合写 ECM、TMT 投行和资本市场结构。",
          "score_total": 23,
          "source_url": "https://fortune.com/2026/06/07/ai-mega-stock-deals-space-x-anthropic/"
        },
        {
          "title": "Tech stocks dive as Fed bets rattle AI rally",
          "summary": "AI 相关股票波动很大，适合写给想进二级市场、研究、买方的学生，重点讲利率、估值和业务兑现。",
          "score_total": 20,
          "source_url": "https://ca.marketscreener.com/news/tech-stocks-dive-as-fed-bets-rattle-ai-rally-ce7f5dd2dc8dfe26/"
        },
        {
          "title": "Anthropic again calls for pause in global AI development",
          "summary": "和我们当前重点方向相关度偏弱，可先不优先写。",
          "score_total": 18,
          "source_url": "https://www.barrons.com/news/anthropic-again-calls-for-pause-in-global-ai-development-399234cc"
        },
        {
          "title": "特朗普团队对 OpenAI 的态度与潜在干预空间引发讨论",
          "summary": "适合继续跟进，政策走向和落地细节还不清楚。",
          "score_total": 19,
          "source_url": "https://techcrunch.com/2026/06/07/trump-administration-might-take-equity-stake-in-openai/"
        }
      ]
    },
    {
      "date": "2026-06-04",
      "file": "outputs/daily/2026-06-04-topic-radar.md",
      "top_topics": [
        {
          "title": "1）SpaceX 固定 IPO 定价，华尔街大行连夜做高净值路演：这不是八卦，而是 ECM、TMT 投行、一级市场叙事回暖的信号",
          "score_total": 28,
          "sources": [
            "Reuters，2026-06-04",
            "Reuters，2026-06-04"
          ],
          "source_urls": [
            "https://uk.marketscreener.com/news/wall-street-giants-tout-spacex-in-glitzy-pre-ipo-investor-events-ce7f5ddddb88f424",
            "https://uk.marketscreener.com/news/spacex-fixed-priced-ipo-ends-flat-in-market-debut-ce7f5ddddf08f427"
          ],
          "summary": "Reuters 6 月 4 日报道，SpaceX 在上市前夜以固定价格完成发行，盘前还出现了由 Bank of America、JPMorgan、Morgan Stanley 面向高净值客户的密集推介活动。 同日另一篇 Reuters 报道显示，SpaceX 首日交易基本持平，没有出现极端暴涨。 这说明市场更关注的是顶级资产如何被销售、定价、分配，而不只是首日情绪。",
          "why_it_matters": "对想冲金融高薪赛道的学生，这条新闻的价值不在 SpaceX 本身，而在 一级发行、ECM、TMT 投行、资本市场销售、财富管理分销 重新成为热门叙事。 对想进科技的学生，这也说明太空、国防科技、硬科技平台开始重新进入资本市场中心视野，未来校招叙事可能不只围绕纯软件。",
          "job_signal": "可核实事实：SpaceX 完成 IPO；多家华尔街大行参与高净值投资者推介；首日交易表现平稳。 推断：如果下半年大型 IPO 继续推进，ECM、TMT IB、资本市场、投资者关系、一级市场研究 的内容热度和求职关注度会抬升；但这不等于立刻出现大规模校招扩招，具体 headcount 需要二次核实。"
        },
        {
          "title": "2）Helion 为给微软建聚变电站再融 4.65 亿美元：AI 基建的瓶颈已经从模型卷到电力，电气、能源和项目融资会更值钱",
          "score_total": 29,
          "sources": [
            "TechCrunch，2026-06-04"
          ],
          "source_urls": [
            "https://techcrunch.com/2026/06/04/helion-the-sam-altman-backed-fusion-startup-raises-465m-to-build-a-power-plant-for-microsoft/"
          ],
          "summary": "TechCrunch 6 月 4 日报道，Helion 完成 4.65 亿美元新融资，用于推进为微软供电的聚变发电项目。 报道把重点放在一件事上：AI 计算扩张正在把电力和能源建设推到核心位置，电不是配角，而是 AI infra 的硬约束。",
          "why_it_matters": "很多学生把 AI 求职理解成模型、应用、agent，但真正能持续吸纳资金和岗位的链条，越来越包含 电力系统、数据中心能源、硬件部署、utility interface、项目融资、基础设施法务与许可。 对 EE、ME、CE、CS 以及想进 infra finance 的学生，这条新闻比单纯大模型发布更接近真钱流向。",
          "job_signal": "可核实事实：Helion 于 6 月 4 日宣布新融资，用于推进面向微软的电站建设。 推断：未来更值得准备的，不只是 AI 软件岗，还包括 energy systems、power electronics、grid interface、project development、infra finance；但具体到 Helion 或微软生态的 early career 岗位数量，仍需二次核实。"
        },
        {
          "title": "3）Blackstone 与 Partners Group 的私募信贷产品都出现更高赎回压力：高薪买方不是没机会，而是岗位重心更偏风控、信用与流动性",
          "score_total": 26,
          "sources": [
            "Reuters，2026-06-04",
            "Reuters，2026-06-04"
          ],
          "source_urls": [
            "https://in.marketscreener.com/news/private-credit-funds-face-renewed-withdrawals-in-second-quarter-ce7f5ddcd18cf72d",
            "https://www.marketscreener.com/news/partners-group-imposes-1-3-billion-cap-on-second-quarter-withdrawals-from-private-credit-fund-7c289c3057e7f88c"
          ],
          "summary": "Reuters 6 月 4 日报道，二季度私募信贷基金再次面临更高提款申请，Blackstone 与 Partners Group 相关产品都成为关注点。 Partners Group 当天还披露，对其一只私募信贷基金的二季度赎回设置了 13 亿美元上限。 这不是简单的坏消息，而是在提醒市场：高收益资产管理故事仍在，但流动性管理和信用风险重新成为核心。",
          "why_it_matters": "很多学生对 buy side 的认知过于单一，只看到薪资和 prestige，看不到不同市场环境下岗位需求会从 deal execution 转向 underwriting、portfolio monitoring、risk、restructuring、LP communication。 如果你想走 private credit、special sits、distressed、RX、credit research，这类新闻比基金募了多少钱更有求职判断价值。",
          "job_signal": "可核实事实：Reuters 报道二季度私募信贷赎回压力上升，Partners Group 对相关基金设置提款上限。 推断：未来一段时间，信用类岗位中更值得准备的是 风险分析、资产组合监控、流动性、违约与重组认知；但这不等于行业整体缩招或不招新人，具体招聘趋势需要二次核实。"
        }
      ],
      "alternatives": [
        {
          "title": "Ramp 以 440 亿美元估值完成 7.5 亿美元融资",
          "summary": "AI 与企业财务软件、fintech automation、growth product、risk infra 仍有资金追捧。",
          "score_total": 25,
          "source_url": ""
        },
        {
          "title": "美国众议院小组提出联邦优先的 AI 监管草案",
          "summary": "和我们当前重点方向相关度偏弱，可先不优先写。",
          "score_total": 22,
          "source_url": ""
        },
        {
          "title": "Supabase 融资 5 亿美元，估值 40 亿美元",
          "summary": "数据库、开发者工具、agent backend、infra product 仍是 AI 时代的底层受益环节。",
          "score_total": 24,
          "source_url": ""
        },
        {
          "title": "Quantinuum 在纳斯达克首秀，估值约 176 亿美元",
          "summary": "适合做量子计算求职科普，但对大多数留学生仍太前沿、转化门槛高。",
          "score_total": 21,
          "source_url": ""
        },
        {
          "title": "S&P 500 不为大型 IPO 开绿灯，SpaceX 暂无快速纳入可能",
          "summary": "可延展为 被动资金、指数规则、资本市场结构 教学内容，适合金融科普号二创。",
          "score_total": 20,
          "source_url": ""
        },
        {
          "title": "Blackstone 旗下 BREDS 产品二季度赎回升至 4.3%",
          "summary": "可单独拆成 private credit 风控、流动性、基金结构课程型内容。",
          "score_total": 23,
          "source_url": ""
        },
        {
          "title": "美国银行监管机构向国会提交放松监管议程",
          "summary": "中长期利好银行创新和业务扩张叙事，可引到 bank strategy、运营协调、流程系统，但短期信号偏弱。",
          "score_total": 20,
          "source_url": ""
        },
        {
          "title": "Helion 话题在公开社区有讨论，但集中在技术可行性争议，不足以作为求职事实依据",
          "summary": "可用来说明学生对 AI 能源赛道认知不足，但不建议把社区争论当作主线。",
          "score_total": 18,
          "source_url": ""
        }
      ]
    },
    {
      "date": "2026-06-03",
      "file": "outputs/daily/2026-06-03-topic-radar.md",
      "top_topics": [
        {
          "title": "1) Goldman 上调 AI 数据中心资本开支预期：最先受益的不只是码农，而是数据中心融资、基础设施投资和电力链条",
          "score_total": 29,
          "sources": [],
          "source_urls": [],
          "summary": "Reuters 6 月 3 日报道，Goldman Sachs 在当天 note 中表示，随着 AI 驱动的数据中心建设持续加速，未来几年私募基础设施资本和房地产资本将在融资中扮演更大角色。 Goldman 还把四大 hyperscaler 在 2025-2030 财年间的合计资本开支预测，从 4.5 万亿美元 上调到 5.3 万亿美元。 这不是单纯的科技投资新闻，而是资本市场在告诉你：AI 已经从模型故事，变成土地、电力、建筑、设备、ABS、私募信贷、项目融资一起联动的超级基础设施赛道。",
          "why_it_matters": "很多想进高薪金融的学生只盯传统投行组别，但这条新闻释放的是更宽的机会带。 当 AI 数据中心进入大规模融资阶段，受益的并不只是一线模型公司，也包括 infra PE、project finance、IB power & utilities、REIT / real assets、DCM、structured finance 等金融岗位。 对理工科学生，这也说明如果你不想卷 frontier lab，往 data center、energy、cloud infra、power systems、facility tech 这些更落地的方向做项目，反而更贴近真钱流向。",
          "job_signal": ""
        },
        {
          "title": "2) Meta 推企业版 AI business agent，还拉出 Enterprise Solutions 团队：留学生更该准备的是企业落地岗，不是只会做 demo",
          "score_total": 29,
          "sources": [],
          "source_urls": [],
          "summary": "Reuters 6 月 3 日报道，Meta 在伦敦 Conversations 大会上发布面向企业的 AI business agent，能够帮商家处理预约、下单、销售转化等日常任务。 报道提到，已有 超过 100 万家企业 使用此前版本的聊天机器人；新版本将扩展到 Instagram，并面向全球各类企业推出。 更值得留意的是，Reuters 明确提到 Meta 在近期 AI 重组中拉出了 Enterprise Solutions 新团队，并同步推出可连接 Shopify、Zendesk、Shopee 等系统的 Business Agent Platform。",
          "why_it_matters": "这条新闻对求职最有用的地方，不是 Meta 又发了一个 agent，而是大厂正在把 AI 从模型能力转向 企业流程、系统集成、guardrails、measurement、付费订阅。 对学生来说，这意味着未来更有机会承接实习 / NG 的，往往不是最难进的研究岗，而是 applied AI、solutions engineering、enterprise product、integrations、trust & safety、analytics 这些把 AI 真正装进企业流程里的岗位。 如果你的项目还停留在聊天机器人 demo，这条新闻其实是在提醒你简历已经落后了。",
          "job_signal": ""
        },
        {
          "title": "3) Broadcom 当天交出 AI 收入 143% 增长：下一波更值钱的简历，不一定在大模型公司，而在 custom chip 和 AI networking",
          "score_total": 29,
          "sources": [
            "当日权威：Broadcom 财报摘要，经 Investing 转引，6 月 3 日：https://za.investing.com/news/stock-market-news/broadcom-reports-48-revenue-growth-in-fiscal-q2-raises-guidance-93CH-4313124",
            "当日社区二次验证，不作事实依据：Reddit `r/stocks` 6 月 3 日高互动讨论：https://www.reddit.com/r/stocks/comments/1tw1xmy/broadcom_stock_slips_on_disappointing_software/",
            "当日社区二次验证，不作事实依据：Reddit `r/MU_Stock` 6 月 3 日讨论：https://www.reddit.com/r/MU_Stock/comments/1tw1kmi/broadcom_avgo_q2_2026_earnings_ai_surge/"
          ],
          "source_urls": [
            "",
            "",
            ""
          ],
          "summary": "Broadcom 在 6 月 3 日发布财报摘要，披露公司 Q2 总收入同比增长 48%。 更关键的是，管理层给出的口径显示 AI semiconductor revenue 为 108 亿美元，同比增长 143%，并预计 Q3 AI 相关半导体收入同比增长将超过 200%。 这说明 hyperscaler 的 AI 开支还在继续流向 custom AI accelerators 和 AI networking，而不是只流向通用 GPU 叙事。",
          "why_it_matters": "很多学生现在一提 AI 求职，只想到 model training 或应用层开发，但 Broadcom 这条线更接近真正的稀缺能力带。 如果资本继续奖励 custom chip 和 networking，未来更抗内卷、也更高薪的岗位会继续往 硬件软件协同、系统性能、网络互连、低层工具链 倾斜。 对 ECE、CE、CS 背景学生，这是一条比纯算法岗更适合做差异化的路径。",
          "job_signal": ""
        }
      ],
      "alternatives": []
    },
    {
      "date": "2026-06-02",
      "file": "outputs/daily/2026-06-02-topic-radar.md",
      "top_topics": [
        {
          "title": "1) SpaceX 冲 1.75 万亿美元 IPO：这不只是马斯克新闻，而是华尔街、航天、卫星通信、AI 基建一起抬价的高薪赛道信号",
          "score_total": 29,
          "sources": [],
          "source_urls": [],
          "summary": "Reuters 6 月 2 日报道，SpaceX 计划将 IPO 目标估值定在 1.75 万亿美元，并采用 all-primary offering 结构，意味着募集资金全部进公司，不给老股东在 IPO 当天套现。 Reuters 同日还提到，公司基础发行规模至少约 750 亿美元，roadshow 预计很快启动，并称这可能开启新一轮 mega IPO 浪潮。",
          "why_it_matters": "对学生最有价值的点不是 买不买，而是 资本市场开始愿意用航天 + 连接 + AI infra 的复合叙事给极高估值。 这会把更多注意力拉向卫星通信、航天软件、网络系统、数据基础设施、硬件可靠性、供应链金融、ECM/IPO 执行这些高薪方向。 对想走金融的学生，这是一个 ECM、IPO、TMT/industrial coverage、private markets 的真实案例；对想走科技/硬件的学生，这是 space-tech 并不只是 aerospace PhD 才能参与 的信号。",
          "job_signal": ""
        },
        {
          "title": "2) HPE 单日大涨近 30%，把长期目标提前两年：AI infra 的真钱还在往 server、networking、enterprise rollout 走",
          "score_total": 28,
          "sources": [],
          "source_urls": [],
          "summary": "Reuters 6 月 2 日报道，HPE 股价单日飙升约 28%-29%，因为公司业绩与展望显示 AI server 和 data center networking 需求强劲，长期财务目标被提前两年兑现。 报道还提到，HPE 把 2026 财年收入增长预期上调至 29%-33%，networking segment 增长预期上调至 72%-75%，并强调企业客户正在把 agentic AI 当成核心 workload。",
          "why_it_matters": "很多学生现在一提 AI 就只想到模型公司，但真正能吸纳大量工程、产品、解决方案和售前岗位的，往往是 卖算力、卖服务器、卖网络、卖企业集成 的公司。 对留学生来说，这条新闻的价值是帮助大家从 只会调 API 的项目思路，转向 enterprise AI deployment、infra、systems、solution architecture。 这类公司对 intern / new grad 的门槛结构，也往往比 frontier lab 更现实。",
          "job_signal": ""
        },
        {
          "title": "3) Nvidia 说 CPU/GPU 供给足以支撑强劲增长，Marvell 被点名为下一个万亿美元公司：AI 求职重心继续向芯片互连、custom silicon、系统能力倾斜",
          "score_total": 28,
          "sources": [],
          "source_urls": [],
          "summary": "Reuters 6 月 2 日报道称，Jensen Huang 表示 Nvidia 已为 CPU 和 GPU 的强劲增长锁定足够供应，虽然供应约束仍在。 同一天，Reuters 还报道，Marvell 因被黄仁勋点名为 下一个万亿美元公司 而大涨，背后逻辑是其 custom AI chips + interconnect technologies 正成为大型 AI data center 的关键基础设施。",
          "why_it_matters": "这说明 AI 人才需求并没有只集中在模型层，而是继续往 芯片、网络、互连、系统优化、custom silicon、performance 这些更底层的岗位扩散。 对非顶尖研究背景的学生，这反而是好消息，因为这些岗位更看重 ECE / CE / CS 的系统能力、性能意识、硬件软件协同，而不一定要求你先有 frontier model 光环。",
          "job_signal": ""
        }
      ],
      "alternatives": []
    },
    {
      "date": "2026-06-01",
      "file": "outputs/daily/2026-06-01-topic-radar.md",
      "top_topics": [
        {
          "title": "1) Anthropic 在 6 月 1 日递交保密 IPO 文件：这不是资本市场八卦，而是 AI 高薪岗位从 私募叙事 进入 公开市场叙事",
          "score_total": 29,
          "sources": [],
          "source_urls": [],
          "summary": "",
          "why_it_matters": "对还没毕业的学生，这条新闻最重要的不是 能不能买股票，而是 AI 公司的人才叙事开始接受公开市场审视。这通常意味着公司会更重视 revenue narrative、enterprise adoption、go-to-market、基础设施效率、基础设施效率与企业交付，而不再只是研究团队的技术故事。 也就是说，AI 求职不该只盯 research scientist。更现实的新增机会解释框架是：平台工程、推理优化、企业交付、系统稳定性、产品分析、解决方案工程、技术 PM 会更有存在感。",
          "job_signal": ""
        },
        {
          "title": "2) Quantinuum 上调 IPO 规模、估值冲到 143 亿美元：量子不是只给科研 PhD 的故事，华尔街已经开始给它定价",
          "score_total": 26,
          "sources": [],
          "source_urls": [],
          "summary": "",
          "why_it_matters": "今天很多学生把 量化、量子、AI、HPC 当成完全分开的赛道，但资本市场给量子公司定价，意味着 高性能计算、底层软件、误差校正、编译器、数值模拟、算法工程 这些技能会更容易被看见。 对还没毕业的留学生，这类内容尤其适合吸引两类人：一类是数学/物理/EECS 背景但不想只去学术圈的人；另一类是想进高薪前沿赛道、但又打不过纯大模型竞争的人。",
          "job_signal": ""
        },
        {
          "title": "3) Nvidia 在 6 月 1 日把 AI 推进到本地 PC：下一波机会不只在训练大模型，而在端侧 agent、系统优化和 AI 设备生态",
          "score_total": 25,
          "sources": [],
          "source_urls": [],
          "summary": "",
          "why_it_matters": "这条新闻的真正价值在于，它把 AI 机会从 云上大模型 重新拉回 端侧推理、系统资源调度、芯片协同、设备体验、agent workflow。 对学生来说，这意味着你即使进不了 frontier lab，也依然可以去抢一大条更现实的岗位链：edge AI、performance engineering、device software、embedded/firmware、Windows/macOS agent 工具、开发者生态。",
          "job_signal": ""
        }
      ],
      "alternatives": []
    },
    {
      "date": "2026-05-31",
      "file": "outputs/daily/2026-05-31-topic-radar.md",
      "top_topics": [
        {
          "title": "1) SoftBank 在法国落地 1GW AI 数据中心园区：AI infra 的钱不是概念，是电力、网络、机房与运维岗位链条",
          "score_total": 27,
          "sources": [],
          "source_urls": [],
          "summary": "",
          "why_it_matters": "你不一定要去欧洲工作，这条信息的价值在于：AI 增长的下一阶段更像基础设施周期，而不是单纯模型竞赛。 对还没毕业的留学生来说，AI infra 的岗位链条更可迁移：云、数据中心、电力与冷却、网络与分布式系统、SRE/可靠性、供应链与项目管理。哪怕最终投美国岗位，技能栈依旧通用。",
          "job_signal": ""
        },
        {
          "title": "2) 非农前夜的交易逻辑：利率路径和债券收益率才是金融高薪岗位的底层变量",
          "score_total": 25,
          "sources": [],
          "source_urls": [],
          "summary": "",
          "why_it_matters": "金融高薪赛道的 entry-level 机会很少是突然放出来的：它常常先体现在 波动变大、业务更忙、风控更紧、客户更活跃。 你要写的不是 宏观预测，而是 教学生如何读懂交易世界的语言：非农、通胀、收益率曲线与波动率如何影响 S&T、宏观策略、量化研究、风险管理、以及投行融资窗口。",
          "job_signal": ""
        },
        {
          "title": "3) 5/31 留学生身份焦虑的真实问题清单：律师 AMA 里大家问的不是政策条文，是怎么活过下一步",
          "score_total": 28,
          "sources": [],
          "source_urls": [],
          "summary": "",
          "why_it_matters": "身份话题的阅读量高，但大部分账号只会制造焦虑；你的差异化是把焦虑翻译成可执行工具：时间线、材料清单、雇主沟通包、备选路径决策树。 对还没毕业的学生，这能直接影响 offer 选择与投递策略：优先投 sponsor 成熟、流程清晰、HR 能对接 immigration counsel 的雇主（需要二次核实）。",
          "job_signal": ""
        }
      ],
      "alternatives": [
        {
          "title": "SoftBank 1GW 项目拆成 6 类岗位：从 SWE 到数据中心运维，怎么选更适合留学生",
          "summary": "（基于 Top1 二创，2026-05-31）复用 Top1 来源",
          "score_total": 21,
          "source_url": ""
        },
        {
          "title": "AI infra 简历怎么写才像懂系统：把项目从 调包 变成 交付",
          "summary": "（基于 Top1 二创，2026-05-31）复用 Top1 来源",
          "score_total": 20,
          "source_url": ""
        },
        {
          "title": "非农-收益率-波动率：做一个 1 小时就能复现的 event study 作品集",
          "summary": "（基于 Top2 二创，2026-05-31）复用 Top2 来源",
          "score_total": 20,
          "source_url": ""
        },
        {
          "title": "投行/量化面试更爱问什么：用 Reuters 的市场关注点反推题库",
          "summary": "（基于 Top2 二创，2026-05-31）复用 Top2 来源",
          "score_total": 19,
          "source_url": ""
        },
        {
          "title": "OPT/STEM OPT 焦虑的 10 个高频问题：做成置顶 FAQ 才能长期涨粉",
          "summary": "（基于 Top3 二创，2026-05-31）复用 Top3 来源",
          "score_total": 19,
          "source_url": ""
        },
        {
          "title": "身份沟通包模板：如何让 HR 快速理解你的时间线并减少误解",
          "summary": "（基于 Top3 二创，2026-05-31）复用 Top3 来源",
          "score_total": 19,
          "source_url": ""
        },
        {
          "title": "社区二次验证：OPT 等待与流程困惑在 5/31 集中爆发，适合做一篇 不焦虑的应对清单",
          "summary": "（Reddit r/f1visa，2026-05-31）https://www.reddit.com/r/f1visa/comments/1tszakh/opt_and_what_bothers_me/",
          "score_total": 18,
          "source_url": ""
        }
      ]
    },
    {
      "date": "2026-05-28",
      "file": "outputs/daily/2026-05-28-topic-radar.md",
      "top_topics": [
        {
          "title": "1) Goldman 说 2026 并购量有望逼近 2021 纪录：投行不是突然开岗，而是先从 deal pipeline 变热开始",
          "score_total": 27,
          "sources": [],
          "source_urls": [],
          "summary": "",
          "why_it_matters": "对尚未毕业、还在冲 IB Summer Analyst / Analyst 的同学来说，最痛苦的不是没准备，而是不知道窗口期到底有没有打开。 与其等岗位帖出现，不如先抓住最早的机会信号：大行公开口径从保守转向乐观，通常意味着组内执行压力变大，networking 和 referral 更容易从礼貌聊天变成真实推进（是否扩招仍需二次核实）。",
          "job_signal": ""
        },
        {
          "title": "2) Anthropic 融资 650 亿美金、估值冲到 9650 亿：对留学生更重要的是 这意味着 AI 钱继续砸在算力与产品化上",
          "score_total": 25,
          "sources": [],
          "source_urls": [],
          "summary": "",
          "why_it_matters": "这不是让你去猜谁赢谁输，而是给你一个判断：在资金继续堆到头部的阶段，实习与 NG 更可能出现的岗位类型往往不是纯研究，而是把模型变成可卖的产品与可控的工程系统。 如果你准备 2026-2027 的实习/NG，作品集与简历更应该对齐可复用、可上线、可观测、可交付 的能力，而不是只堆 demo。",
          "job_signal": ""
        },
        {
          "title": "3) USCIS 把 I-485 AOS 重新框定为 extraordinary relief：留学生身份规划里的最大坑是 把可办 当成稳过",
          "score_total": 28,
          "sources": [],
          "source_urls": [],
          "summary": "",
          "why_it_matters": "尚未毕业的留学生常见误区是只盯 H-1B，而忽略了长期身份路径中，任何 I-485/AOS 相关的不确定性都会反向影响 选雇主、选城市、选入职节奏、是否换工作。 对雇主视角（尤其是中小公司）来说，身份不确定性上升会强化他们对 offer start date、背景调查、remote/onsite 的谨慎偏好，留学生必须提前准备 风险沟通包。",
          "job_signal": ""
        }
      ],
      "alternatives": [
        {
          "title": "Snowflake 追加 60 亿美金押注 AWS：企业 AI 工作负载正在变成长期基础设施支出",
          "summary": "（DataCenterKnowledge，2026-05-28）https://www.datacenterknowledge.com/infrastructure/snowflake-s-6b-aws-bet-signals-new-era-of-enterprise-ai-infrastructure",
          "score_total": 21,
          "source_url": ""
        },
        {
          "title": "AI 是否在压缩 entry-level：把焦虑翻译成留学生的简历与投递策略",
          "summary": "（ABC News，2026-05-28）https://abcnews.com/Business/ai-blame-hiring-woes-faced-college-graduates/story?id=133309225",
          "score_total": 20,
          "source_url": ""
        },
        {
          "title": "RBC 二季报靠 trading boost：波动市里哪些金融岗位更吃香",
          "summary": "（Reuters，2026-05-28，经 MarketScreener 转引）https://www.marketscreener.com/news/royal-bank-of-canada-s-quarterly-profit-rises-on-trading-boost-ce7f5ddad980fe24",
          "score_total": 20,
          "source_url": ""
        },
        {
          "title": "全球市场因海湾紧张回撤：地缘波动如何影响 S&T 与风控岗位的需求叙事",
          "summary": "（Reuters，2026-05-28，经 LSE/Reuters 转引）https://www.lse.co.uk/news/global-markets-stocks-knocked-back-from-record-highs-as-gulf-tensions-flare-oara445qa60nbbc.html",
          "score_total": 19,
          "source_url": ""
        },
        {
          "title": "社区高互动：Anthropic 估值与泡沫争议爆发，读者真正关心的是薪资、门槛与转型路径",
          "summary": "（Reddit r/technology，2026-05-28）https://www.reddit.com/r/technology/comments/1tqdcku/anthropic_secures_965_billion_valuation_after/",
          "score_total": 19,
          "source_url": ""
        },
        {
          "title": "同主题延伸：用 Anthropic 融资做 AI infra 作品集改造教程",
          "summary": "（基于 Top2 二创，2026-05-28）复用 Top2 来源",
          "score_total": 19,
          "source_url": ""
        },
        {
          "title": "同主题延伸：用 Goldman deal pipeline 写 IB 求职问法与信息收集表",
          "summary": "（基于 Top1 二创，2026-05-28）复用 Top1 来源",
          "score_total": 19,
          "source_url": ""
        }
      ]
    },
    {
      "date": "2026-05-27",
      "file": "outputs/daily/2026-05-27-topic-radar.md",
      "top_topics": [
        {
          "title": "1) 摩根大通 CEO 说 IB 手续费二季度或增 10%+：这不是财经八卦，是投行岗位热度的前置指标",
          "score_total": 27,
          "sources": [],
          "source_urls": [],
          "summary": "",
          "why_it_matters": "你投 IB 很容易陷入只看开没开岗，但更关键的是判断窗口期：业务预期回暖时，暑期实习转正与 New Grad pipeline 往往更愿意给 buffer。 对非名校/非 target 的同学，景气度改善时 networking 的转化率通常更高，特别是 Coverage/Industry 组和部分产品组（ECM/DCM/LevFin）在 deal flow 复苏阶段更需要新人做执行。",
          "job_signal": ""
        },
        {
          "title": "2) 前 DeepMind/Apple/OpenAI 等研究员做 AI 产品反馈闭环：下一波更缺的不是写模型的人，而是能把反馈做成数据的人",
          "score_total": 27,
          "sources": [],
          "source_urls": [],
          "summary": "",
          "why_it_matters": "这条新闻可以直接翻译成简历与选方向：做一个能上线、能监控、能迭代的数据闭环项目，比单次跑分更贴近面试。 对需要 sponsor 的同学：越靠近企业真实业务的 AI 工程角色（ML platform、data、evals、数据质量）通常更容易解释业务价值与业务边界（是否 sponsor 仍需二次核实）。",
          "job_signal": ""
        },
        {
          "title": "3) 身份痛点当日爆发：OPT/STEM OPT 时间线 megathread 高互动，真正需要的是一份可执行的雇主沟通与风险预案",
          "score_total": 27,
          "sources": [],
          "source_urls": [],
          "summary": "",
          "why_it_matters": "你的风险不是没 offer，而是 start date 和授权文件对不上，导致雇主撤 offer 或推迟入职。 很多同学在最后 2-4 周才和 HR 解释 OPT/STEM OPT 规则，时间越紧沟通成本越高。",
          "job_signal": ""
        }
      ],
      "alternatives": [
        {
          "title": "华尔街期指继续被 AI 情绪推着走：这类市场叙事如何影响金融岗结构",
          "summary": "（Reuters，2026-05-27，经 MarketScreener 转引）https://ca.marketscreener.com/news/wall-st-futures-rise-on-ai-optimism-investors-optimistic-on-mideast-truce-ce7f5ad2d18ff121",
          "score_total": 20,
          "source_url": ""
        },
        {
          "title": "DHS 拟在部分机场调整入境处理：国际出入境不确定性上升下的留学生旅行风险提醒",
          "summary": "（Reuters，2026-05-26 发布且 2026-05-27 修改，经 MarketScreener 转引）https://ca.marketscreener.com/news/us-drawing-up-plans-to-halt-immigration-customs-processing-at-sanctuary-city-airports-ce7f5ad2df88f627",
          "score_total": 19,
          "source_url": ""
        },
        {
          "title": "AI chat fatigue 上了 HN 前排：企业开始讨论 AI 工作流设计，利好哪些岗位",
          "summary": "（Hacker News 当日高互动二次线索，经 Developers Digest 汇总，2026-05-27）https://www.developersdigest.tech/blog/ai-chat-fatigue-verifiable-workflows",
          "score_total": 19,
          "source_url": ""
        },
        {
          "title": "GitHub Actions 故障讨论爆发：CI 稳定性正在变成工程组织的硬指标",
          "summary": "（社区高互动二次线索，2026-05-27）https://gearbriefly.com/2026/05/27/github-actions-outage-ci-release-risk/",
          "score_total": 18,
          "source_url": ""
        },
        {
          "title": "r/ArtificialInteligence 高赞讨论：裁员到底是不是 AI 的锅",
          "summary": "（Reddit 当日高互动，2026-05-27）https://www.reddit.com/r/ArtificialInteligence/comments/1tovwzx/mit_report_basically_confirms_ai_isnt_the_real/",
          "score_total": 19,
          "source_url": ""
        },
        {
          "title": "用 Reuters 表态写 IB 求职行动清单的延伸版：如何问出 deal flow 与 headcount",
          "summary": "（基于 Top1 二创，2026-05-27）复用 Top1 来源",
          "score_total": 19,
          "source_url": ""
        },
        {
          "title": "Trajectory 方向延伸：做一个可展示的线上评测与回滚 demo，如何对标 ML Platform 面试",
          "summary": "（基于 Top2 二创，2026-05-27）复用 Top2 来源",
          "score_total": 20,
          "source_url": ""
        }
      ]
    },
    {
      "date": "2026-05-26",
      "file": "outputs/daily/2026-05-26-topic-radar.md",
      "top_topics": [
        {
          "title": "1) Micron 破 1T 市值背后：AI 竞争正在从算力转向内存与供应链，这是硬件岗的温度计",
          "score_total": 27,
          "sources": [
            "Reuters（2026-05-26，经 Investing.com 转引）：https://m.investing.com/news/stock-market-news/micron-joins-1-trillion-club-as-ai-race-powers-memory-chip-boom-4710313?ampMode=1",
            "事件摘要（写给留学生看的版本）",
            "Reuters 报道：Micron 在 AI 需求推动下，股价大涨并首次触及 1 万亿美元市值。",
            "这不是股评选题，而是一个行业结构信号：AI 供应链里，内存与带宽不再是配角，正在变成限制因素之一。",
            "为什么对美国留学生重要",
            "许多同学把 AI 求职等同于大模型算法岗，但产业真正扩张时，往往先体现在 硬件与供应链 的订单与定价能力上。",
            "对实习与 NG 更友好的是 工程化岗位：验证与量产、固件与系统、性能分析、数据中心侧的可靠性与成本。",
            "职业机会信号（可写成判断框架）",
            "适合平台",
            "两者都适合（小红书做方向选择焦虑钩子；公众号做硬件到数据中心的岗位地图）。"
          ],
          "source_urls": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "summary": "",
          "why_it_matters": "许多同学把 AI 求职等同于大模型算法岗，但产业真正扩张时，往往先体现在 硬件与供应链 的订单与定价能力上。 对实习与 NG 更友好的是 工程化岗位：验证与量产、固件与系统、性能分析、数据中心侧的可靠性与成本。 职业机会信号（可写成判断框架） 1. 从 AI 芯片到 AI 系统：内存、互连、散热、功耗、可靠性都会决定模型能不能规模化跑起来。 2. 机会更可能出现在交叉地带：软件同学可以切入 性能工程、系统软件、分布式存储、数据中心可观测性。 3. 简历与项目的写法要换：把项目写成 提升吞吐、降低延迟、节省成本、提高稳定性 的指标闭环，而不是只写模型指标。 适合平台 两者都适合（小红书做方向选择焦虑钩子；公众号做硬件到数据中心的岗位地图）。 小红书标题（3 个） 1. Micron 破 1T 不是股价新闻，是 AI 硬件岗变热的信号 2. AI 不是只有大模型：内存和带宽才是下一波机会 3. 不会训练 SOTA 也能进 AI：硬件与系统岗怎么准备 公众号标题（2 个） 1. Micron 破 1T：AI 进入内存与供应链竞赛，留学生怎么画硬件岗位地图 2. 从算力到内存：AI 产业链里更适合实习和 NG 的岗位在哪里 内容角度（运营视角） 用 Micron 破 1T 做入口，输出一张 AI 硬件到数据中心岗位地图：内存与互连是什么、对应什么岗位、项目怎么做、简历怎么写。 可引导的求职方向 Hardware Engineer、System Software、Performance Engineer、SRE（硬件/机房方向）、Supply C…",
          "job_signal": ""
        },
        {
          "title": "2) I Squared 买下 10 个数据中心：AI 推理时代的钱在涌向机房，留学生该盯的不是模型岗而是基础设施链条",
          "score_total": 28,
          "sources": [
            "Reuters（2026-05-26，经 Investing.com 转引）：https://www.investing.com/news/stock-market-news/i-squared-bets-on-ai-inference-with-225-million-data-center-buy-from-cogent-4709868",
            "事件摘要（写给留学生看的版本）",
            "Reuters 报道：投资机构 I Squared Capital 用约 2.25 亿美元现金从 Cogent Fiber 收购 10 处数据中心设施，押注 AI 基础设施与推理需求。",
            "对求职最关键的翻译：AI 进入推理规模化阶段后，瓶颈更多在 电力、制冷、网络、运维、可靠性 与融资能力。",
            "为什么对美国留学生重要",
            "数据中心是 AI 产业链里 最真实、最刚性 的扩张方向之一，岗位更偏 工程与交付，也更容易被拆解成可准备的技能路径。",
            "对商科与交叉背景同学也友好：基础设施投资会带来 project finance、infra PE、并购与估值、采购与交付、能源与碳排核算等需求。",
            "职业机会信号（可写成判断框架）",
            "适合平台",
            "小红书更适合（强钩子：AI 推理时代的真实岗位在哪里）；公众号也适合（拆解数据中心链条与职业路径）。"
          ],
          "source_urls": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "summary": "",
          "why_it_matters": "数据中心是 AI 产业链里 最真实、最刚性 的扩张方向之一，岗位更偏 工程与交付，也更容易被拆解成可准备的技能路径。 对商科与交叉背景同学也友好：基础设施投资会带来 project finance、infra PE、并购与估值、采购与交付、能源与碳排核算等需求。 职业机会信号（可写成判断框架） 1. 资本在买数据中心，意味着下游会追着要 电力与可靠性：SRE、capacity planning、site reliability、network、security 机会更明确。 2. 对新人更可落地：你可以用 开源工具 + 云资源 做出 可观测性、容量规划、成本优化 的作品集，而不是卷模型训练。 3. 招聘更可能出现在 供应商与承包链：电力设备、制冷、能效软件、机房运维与网络服务商。 适合平台 小红书更适合（强钩子：AI 推理时代的真实岗位在哪里）；公众号也适合（拆解数据中心链条与职业路径）。 小红书标题（3 个） 1. AI 推理时代真正缺人的是数据中心：留学生别只盯模型岗 2. 资本在买机房：AI infra 岗位地图给你画出来了 3. 你做的 LLM 项目不值钱？换成可观测性和容量规划就很值钱 公众号标题（2 个） 1. I Squared 买下数据中心：AI infra 的岗位链条怎么拆给留学生用 2. 推理规模化时代：电力、制冷、网络、运维分别对应哪些高薪岗位 内容角度（运营视角） 用 买数据中心 作为机会信号，做一张 数据中心岗位链条图 + 作品集路线图：从系统与网络到能效与成本。 可引导的求职方向 Data Center Op…",
          "job_signal": ""
        },
        {
          "title": "3) Stord 融资 2.5 亿美金 + Stord Labs：物理世界 AI 正在落地，最容易转化成实习项目的是仓储与自动化",
          "score_total": 26,
          "sources": [
            "Reuters（2026-05-26，经 MarketScreener 转引）：https://www.marketscreener.com/news/logistics-startup-stord-raises-250-million-at-3-billion-valuation-ce7f5addd08bf624",
            "事件摘要（写给留学生看的版本）",
            "Reuters 报道：物流公司 Stord 宣布融资接近 2.5 亿美元，估值约 30 亿美元，并启动 Stord Labs，用真实履约数据测试 agentic AI、机器人与自动化。",
            "关键翻译：AI 正在从写代码与写文案，走向 物理世界的效率与成本，这类公司更需要能把系统跑稳的人。",
            "为什么对美国留学生重要",
            "物理 AI 更像 复杂系统工程：数据质量、流程约束、实时性、容错与成本都要同时考虑，对实习生来说反而更容易做出差异化项目。",
            "这是把 ML / SWE / OR 运筹 与 供应链结合的路径，适合不想卷纯模型岗但仍想吃到 AI 红利的同学。",
            "职业机会信号（可写成判断框架）",
            "适合平台",
            "小红书更适合（物理 AI 很好讲成 真实高薪岗位）；公众号适合做深度拆解与项目路线图。"
          ],
          "source_urls": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "summary": "",
          "why_it_matters": "物理 AI 更像 复杂系统工程：数据质量、流程约束、实时性、容错与成本都要同时考虑，对实习生来说反而更容易做出差异化项目。 这是把 ML / SWE / OR 运筹 与 供应链结合的路径，适合不想卷纯模型岗但仍想吃到 AI 红利的同学。 职业机会信号（可写成判断框架） 1. 资金 + Labs 往往意味着会补齐平台与数据团队（是否扩招需要二次核实）。 2. 更适合新人的岗位画像：Data/Analytics Engineering、ML Platform、Simulation、Warehouse Ops Tech、Product Ops。 3. 作品集方向更明确：用公开数据做 订单预测、库存与路径优化、异常检测、仓内调度模拟。 适合平台 小红书更适合（物理 AI 很好讲成 真实高薪岗位）；公众号适合做深度拆解与项目路线图。 小红书标题（3 个） 1. 物流公司也在搞 AI Labs：留学生更容易拿到的 AI 实习方向来了 2. 不想卷大模型？仓储与自动化的 AI 更容易做出作品集 3. 物理世界 AI 的岗位画像：SWE + 数据 + 运筹一起上 公众号标题（2 个） 1. Stord 融资 + Labs：物理世界 AI 的岗位链条与留学生项目路线图 2. 从履约数据到机器人自动化：更适合实习生切入的 AI 应用方向 内容角度（运营视角） 用 物理世界 AI 的三个硬约束 开篇：实时性、容错、成本，然后给出项目清单与简历包装模板。 可引导的求职方向 Supply Chain Tech、Data Scientist（forecasting…",
          "job_signal": ""
        }
      ],
      "alternatives": [
        {
          "title": "OpenAI CEO Altman 表态 AI 不太可能带来 jobs apocalypse",
          "summary": "可写成 留学生选方向别被恐慌带跑（Reuters，2026-05-26，经 Investing.com 转引）。https://www.investing.com/news/economy-news/openais-altman-says-ai-unlikely-to-lead-to-jobs-apocalypse-4708791",
          "score_total": 21,
          "source_url": ""
        },
        {
          "title": "Terra Quantum 更换 SPAC 伙伴推进约 35 亿美元上市",
          "summary": "量化金融与安全方向可写成 量子安全与企业需求侧岗位（Reuters，2026-05-26，经 StreetInsider 转引）。https://www.streetinsider.com/Reuters/Swiss-based%2BTerra%2BQuantum%2Bchanges%2Bpartner%2Bahead%2Bof%2B%243.5%2Bbillion%2Blisting/26545943.html",
          "score_total": 19,
          "source_url": ""
        },
        {
          "title": "Qualcomm 据报与 ByteDance 达成 AI 数据中心芯片供货",
          "summary": "可写成 AI 数据中心供应链继续加速（Reuters，2026-05-26，经 MarketScreener 转引）。https://www.marketscreener.com/news/qualcomm-strikes-ai-chip-deal-with-tiktok-owner-bytedance-bloomberg-news-reports-ce7f5ad2d989fe26",
          "score_total": 20,
          "source_url": ""
        },
        {
          "title": "S&P 500 与 Nasdaq 刷新收盘新高",
          "summary": "可写成 AI 硬件交易情绪回暖与 校招体感 的关系（Reuters，2026-05-26，经 Investing.com 转引）。https://au.investing.com/news/stock-market-news/sp-500-hits-record-closing-high-on-ai-optimism-micron-joins-1-trillion-club-4456512",
          "score_total": 19,
          "source_url": ""
        },
        {
          "title": "Brent 原油因美方在伊朗的军事行动上行",
          "summary": "可写成 能源与大宗波动下的 风险与交易型岗位（Reuters，2026-05-26，经 MarketScreener 转引）。https://ca.marketscreener.com/news/global-oil-price-gains-3-as-us-military-strikes-on-iran-add-to-peace-deal-uncertainty-ce7f5addda8cf62d",
          "score_total": 19,
          "source_url": ""
        },
        {
          "title": "Yale OISS 发布 USCIS 调整身份政策相关解读提醒",
          "summary": "可写成 留学生身份规划的红线清单（Yale OISS，2026-05-26）。https://oiss.yale.edu/news/uscis-issues-new-policy-guidance-on-adjustment-of-status-applications",
          "score_total": 20,
          "source_url": ""
        },
        {
          "title": "Eli Lilly 收购三家疫苗开发公司，合计交易价值最高近 40 亿美元",
          "summary": "可写成 生物医药与临床数据方向的机会（Reuters，2026-05-26，经 Yahoo Finance 转引）。https://ca.finance.yahoo.com/news/lilly-acquire-three-vaccine-developers-105831332.html",
          "score_total": 19,
          "source_url": ""
        }
      ]
    },
    {
      "date": "2026-05-25",
      "file": "outputs/daily/2026-05-25-topic-radar.md",
      "top_topics": [
        {
          "title": "1) Hedge Fund 在加仓科技，不是追热点：这是给 Quant/ML/Infra 的预算信号",
          "score_total": 26,
          "sources": [
            "Reuters（2026-05-25，经 WSAU 转引）：https://wsau.com/2026/05/25/goldman-says-u-s-hedge-fund-tech-positions-nearing-record-highs/"
          ],
          "source_urls": [
            ""
          ],
          "summary": "",
          "why_it_matters": "很多同学投量化/对冲基金时容易陷入背面经+刷题，但真正影响 offer 的往往是：你能不能解释清楚你做的项目如何服务风控/回测/执行/收益归因。 当资金流向科技/AI，基金更需要会工程化的人：能把数据管道、特征工程、回测框架、监控告警做稳定的人（尤其是 internship/new grad）。",
          "job_signal": ""
        },
        {
          "title": "2) 数据中心的钱在加速流入：AI infra 的真实需求，从电力/制冷/运维开始",
          "score_total": 26,
          "sources": [
            "Reuters（2026-05-25，经 Yahoo Finance 转引）：https://finance.yahoo.com/news/schneider-electric-sees-india-083155492.html"
          ],
          "source_urls": [
            ""
          ],
          "summary": "",
          "why_it_matters": "很多同学把 AI 机会等同于做大模型/算法岗，但现实是：大量预算会流向 AI infra 与数据中心相关的工程岗位，而且这些岗位更偏长期刚需，受短期市场情绪影响更小。 对国际学生而言，这类方向也更容易形成可量化的工程成果（可靠性、能效、成本、延迟、容量规划），简历与面试更好讲清楚。",
          "job_signal": ""
        },
        {
          "title": "3) 企业开始算 AI 的真实账：从用 AI到跑在 AI 上，机会在 LLMOps/FinOps/采购与平台",
          "score_total": 27,
          "sources": [
            "Reuters（2026-05-25，经 Fidelity 转引；本文无法直接访问 Fidelity 页面，需二次核实原文细节）：https://www.fidelity.com/news/article/default/202605250741RTRSNEWSCOMBINED_KBN3RW0R5-OUSBS_1",
            "Reddit r/technology 高互动讨论（2026-05-25，作为社区热度信号）：https://www.reddit.com/r/technology/comments/1kyw89h/microsoft_ai_can_cost_more_than_employees_uber_ceo/"
          ],
          "source_urls": [
            "",
            ""
          ],
          "summary": "",
          "why_it_matters": "当企业进入算 ROI阶段，机会会从只招模型研究扩散到：平台工程、推理成本优化、数据管理、可观测性、FinOps、采购与交付。 这类岗位往往更适合实习/NG 进入：你不必证明自己能训练 SOTA，只要能证明你能把系统跑稳、把成本打下来、把流程做扎实。",
          "job_signal": ""
        }
      ],
      "alternatives": [
        {
          "title": "全球公司在印度的 GCC（全球能力中心）从扩人转向挑人",
          "summary": "AI 让技能结构变化更快（Reuters，2026-05-25，经 The Globe and Mail 转引）。https://www.theglobeandmail.com/business/international-business/article-global-firms-rethink-hiring-at-indias-global-capability-centres/",
          "score_total": 21,
          "source_url": ""
        },
        {
          "title": "AI 野心取决于再培训",
          "summary": "IBM 观点可写成留学生技能升级路线（Reuters，2026-05-25，经 The Economic Times 转引）。https://economictimes.indiatimes.com/tech/artificial-intelligence/indias-ai-ambitions-hinge-on-workforce-reskilling-ibm-india-head/articleshow/121393775.cms",
          "score_total": 20,
          "source_url": ""
        },
        {
          "title": "Pope 呼吁 AI 监管",
          "summary": "和我们当前重点方向相关度偏弱，可先不优先写。",
          "score_total": 19,
          "source_url": ""
        },
        {
          "title": "印度官员谈美国签证议题",
          "summary": "更适合做身份不确定性上升时的投递策略提醒（Reuters，2026-05-25，经 Barron's 转引）。https://www.barrons.com/news/india-voices-concern-over-us-visas-but-sees-alignment-with-rubio-d86d8717",
          "score_total": 20,
          "source_url": ""
        },
        {
          "title": "AI 成本高于员工成本？社区热议背后的真问题",
          "summary": "把讨论转为如何面试回答 AI ROI（Reddit r/technology，2026-05-25 高互动）。https://www.reddit.com/r/technology/comments/1kyw89h/microsoft_ai_can_cost_more_than_employees_uber_ceo/",
          "score_total": 20,
          "source_url": ""
        },
        {
          "title": "数据中心景气度继续外溢到供应链与能效",
          "summary": "围绕 Schneider 相关报道做二创供应链/硬科技岗位地图（Reuters，2026-05-25，经 Yahoo Finance 转引）。https://finance.yahoo.com/news/schneider-electric-sees-india-083155492.html",
          "score_total": 19,
          "source_url": ""
        },
        {
          "title": "GCC/外包/离岸岗位会不会被 AI 替代？",
          "summary": "用 Reuters 文章做留学生如何选择更抗替代岗位的判断（Reuters，2026-05-25，经 The Globe and Mail 转引）。https://www.theglobeandmail.com/business/international-business/article-global-firms-rethink-hiring-at-indias-global-capability-centres/",
          "score_total": 19,
          "source_url": ""
        }
      ]
    },
    {
      "date": "2026-05-24",
      "file": "outputs/daily/2026-05-24-topic-radar.md",
      "top_topics": [
        {
          "title": "1) “财报季快结束了，宏观开始接管”：美股在高位摇晃，利率/通胀/AI 叙事将直接决定今年的招聘方向",
          "score_total": 26,
          "sources": [
            "Reuters（2026-05-24，经 Khaleej Times 转引）：https://www.khaleejtimes.com/business/markets/wall-st-week-ahead-soaring-stocks-could-face-rocky-patch-as-earnings-wind-down-yields-perk-up-3?amp=1"
          ],
          "source_urls": [
            ""
          ],
          "summary": "",
          "why_it_matters": "你在找的不是“某一家公司今天开了多少岗”，而是“今年哪些团队更敢加 headcount”。当宏观不确定性上升时，招聘会从“增量扩张”转向“更强调 ROI 的岗位”：更偏 revenue/效率/风控/成本控制，而不是纯增长叙事。 这类“宏观接管”的阶段，最容易出现两极分化：AI 相关链条继续热（算力、服务器、云、数据平台、效率工具），而对利率敏感/消费敏感的板块会更谨慎。对留学生而言，这决定你该把简历投向“增长故事”还是“现金流故事”。",
          "job_signal": ""
        },
        {
          "title": "2) 油价与美元一起“急刹车”：中东局势缓和预期让市场风险偏好回归——能源交易/宏观策略窗口怎么抓？",
          "score_total": 22,
          "sources": [
            "Reuters（2026-05-24，经 KELO-AM 转引）：https://kelo.com/2026/05/24/stocks-rise-oil-and-dollar-slide-on-middle-east-peace-hopes/"
          ],
          "source_urls": [
            ""
          ],
          "summary": "",
          "why_it_matters": "当油价/汇率成为影响通胀与利率的核心变量时，金融机构里最值钱的能力会更“硬”：宏观研究、量化策略、风控、商品/能源相关交易与数据工程。 对留学生来说，这类周期的机会不是“今天去投能源公司”，而是把自己的能力包装成能服务波动：数据、模型、执行、风险控制、系统稳定性。",
          "job_signal": ""
        }
      ],
      "alternatives": [
        {
          "title": "“PCE 通胀才是下周真正的 Boss”",
          "summary": "把宏观数据日历做成留学生可用的“求职节奏表”（Reuters，2026-05-24，经 Khaleej Times 转引）。https://www.khaleejtimes.com/business/markets/wall-st-week-ahead-soaring-stocks-could-face-rocky-patch-as-earnings-wind-down-yields-perk-up-3?amp=1",
          "score_total": 20,
          "source_url": ""
        },
        {
          "title": "“收益率上行=估值压力”怎么写成面试回答",
          "summary": "用 5 句话把利率传导链讲清楚（Reuters，2026-05-24，经 Khaleej Times 转引）。https://www.khaleejtimes.com/business/markets/wall-st-week-ahead-soaring-stocks-could-face-rocky-patch-as-earnings-wind-down-yields-perk-up-3?amp=1",
          "score_total": 19,
          "source_url": ""
        },
        {
          "title": "AI 仍是市场核心变量，但招聘从“讲故事”转向“算 ROI”",
          "summary": "适合写 AI infra/企业级落地岗位选择（Reuters，2026-05-24，经 Khaleej Times 转引）。https://www.khaleejtimes.com/business/markets/wall-st-week-ahead-soaring-stocks-could-face-rocky-patch-as-earnings-wind-down-yields-perk-up-3?amp=1",
          "score_total": 21,
          "source_url": ""
        },
        {
          "title": "油价回落但不确定性仍在：如何把“情景分析”写进实习作品集",
          "summary": "（Reuters，2026-05-24，经 KELO-AM 转引）。https://kelo.com/2026/05/24/stocks-rise-oil-and-dollar-slide-on-middle-east-peace-hopes/",
          "score_total": 18,
          "source_url": ""
        }
      ]
    },
    {
      "date": "2026-05-21",
      "file": "outputs/daily/2026-05-21-topic-radar.md",
      "top_topics": [
        {
          "title": "1) SpaceX IPO 文件曝光：AI 算力“超级甲方”出现了——Anthropic 月付 $12.5 亿买算力",
          "score_total": 29,
          "sources": [
            "Axios（2026-05-21）：https://www.axios.com/2026/05/21/ai-news-cycle-openai-anthropic-spacex",
            "DCD / DataCenterDynamics（2026-05-21，转述 IPO 文件披露细节，写作时需回到原文件或多方交叉核实）：https://www.datacenterdynamics.com/en/news/spacex-ipo-filing-reveals-anthropic-set-to-pay-musks-firm-125bn-a-month-to-rent-xai-data-center-space/",
            "Reuters（无法直接访问原文时，可用同日转引作线索，但事实点以 SpaceX 公开文件/多方交叉核实为准，且需标注“需要二次核实”）"
          ],
          "source_urls": [
            "",
            "",
            ""
          ],
          "summary": "",
          "why_it_matters": "你在校准备的“AI / SWE / Infra”不只是大厂/创业公司路线：AI 时代的高薪岗位正在往“算力—数据中心—训练平台—可靠性工程”集中，而“谁敢长期签下天价算力合同”本质是行业景气度与用人强度的信号。 IPO 披露把很多“只在圈内聊”的信息变成了公开材料：对你判断 哪些方向更缺人、哪些技能更值钱 更有依据。",
          "job_signal": ""
        },
        {
          "title": "2) 白宫临时叫停/推迟 AI 行政令：AI 安全与监管“要加速但很难拍板”——对求职意味着什么？",
          "score_total": 26,
          "sources": [
            "AP（2026-05-21）：https://apnews.com/article/ee318f35acc8a2c43e47f3ebf26cb459",
            "Axios（2026-05-21，多角度补充）：",
            "https://www.axios.com/2026/05/21/trump-ai-executive-order-postponed-why",
            "https://www.axios.com/2026/05/21/white-house-postpones-ai-eo-signing",
            "Reuters（经 Investing/TradingView 转引，2026-05-21）：",
            "https://www.investing.com/news/stock-market-news/trump-to-sign-order-on-ai-oversight-as-security-fears-mount-among-supporters-4702720",
            "https://www.tradingview.com/news/reuters.com%2C2026%3Anewsml_L6N41X17M%3A0-trump-to-sign-order-on-ai-oversight-as-security-fears-mount-among-supporters/"
          ],
          "source_urls": [
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "summary": "",
          "why_it_matters": "未来 6-18 个月，AI 行业的“增量岗位”不只在模型训练：还会在 AI 安全、评测、红队、隐私、供应链安全 等方向出现结构性需求。 留学生在择业上会遇到现实约束：一些敏感领域可能涉及身份/背景审查；理解政策走向有助于你 避坑 + 选方向（必须提示：具体限制以公司与岗位要求为准）。",
          "job_signal": "企业会更早投入评测、稳定性和风险控制相关工作。 对留学生更现实的启发，是优先准备更工程化、能落地的方向。"
        },
        {
          "title": "3) 美国商务部拟向 9 家量子公司发出 $20 亿“意向书”（含股权/可转债）：量子赛道的招聘与移民路径怎么押？",
          "score_total": 23,
          "sources": [
            "NIST/美国商务部公告（2026-05-21）：https://www.nist.gov/news-events/news/2026/05/department-commerce-announces-letters-intent-9-companies-2-billion",
            "Reuters（经 WSJ/其他媒体转引的同日讨论可作传播辅助，但事实点以官方公告为准）"
          ],
          "source_urls": [
            "",
            ""
          ],
          "summary": "美国商务部宣布将向 9 家量子信息科技公司发出“资金支持意向书（Letters of Intent）”，总额最高 $2B；并明确提到可能采用 股权、可转换债等工具（属于非常强的产业政策信号）。",
          "why_it_matters": "量子不是“离你太远的科研新闻”，它更像是下一阶段的“高端人才争夺战”：一旦联邦资金与产业链成形，对应的 硬件、系统软件、芯片、算法、编译、低温工程、验证测试 都会需要人。 对留学生来说，这类赛道的优势是：更看重硬技能与研究/工程能力；劣势是：可能更敏感、更挑背景要求（必须提醒个案差异）。",
          "job_signal": "1. 资金工具升级=产业化意图强：从 grant 到股权/可转债→更像“把公司做大做强”的打法→更可能扩招工程与产品化岗位（但扩招规模需二次核实）。 2. 跨学科岗位会冒出来：量子 + HPC + 云 + 安全→对 CS/EE/物理交叉背景更友好。 3. 对普通 CS 留学生的机会点：不一定要“会量子物理”，可以从 编译器/系统/分布式/HPC/性能工程 切入。"
        }
      ],
      "alternatives": [
        {
          "title": "SpaceX“CEO for life/超高投票权”控制权结构",
          "summary": "用 IPO 控制权条款给投行/咨询/PE/VC 方向做面试表达训练（Axios，2026-05-21）。https://www.axios.com/2026/05/21/musk-ceo-spacex-control",
          "score_total": 20,
          "source_url": ""
        },
        {
          "title": "“两小时改变 AI 新闻周期”",
          "summary": "把 Anthropic 财务 + SpaceX 算力 + 政策变化串成“岗位结构变化”推演框架（Axios，2026-05-21）。https://www.axios.com/2026/05/21/ai-news-cycle-openai-anthropic-spacex",
          "score_total": 21,
          "source_url": ""
        },
        {
          "title": "SpaceX 级别 IPO 的外溢：ECM/IPO 项目密度怎么影响校招",
          "summary": "从“项目储备—团队负荷—新人机会”写投行判断（Reuters 转引，2026-05-21，事实以正式文件为准）。https://uk.marketscreener.com/news/bound-for-mars-elon-musk-s-spacex-unveils-filing-for-blockbuster-ipo-ce7f5ad9df8ff022",
          "score_total": 19,
          "source_url": ""
        },
        {
          "title": "AI 编程热潮引发生产事故讨论",
          "summary": "用“AI coding + 可靠性/SRE”做岗位切入（VentureBeat，2026-05-21）。https://venturebeat.com/technology/resolve-ai-says-the-ai-coding-boom-is-breaking-production-systems-it-wants-to-fix-that/",
          "score_total": 20,
          "source_url": ""
        },
        {
          "title": "SpaceX IPO 外溢效应：欧洲航天股走强",
          "summary": "适合做“航天/卫星/通信产业链岗位地图”（Reuters 转引，2026-05-21）。https://www.stocktitan.net/news/RL/spacex-ipo-filing-lifts-european-space-stocks-jkl4xo43mt1c.html",
          "score_total": 18,
          "source_url": ""
        },
        {
          "title": "AI 安全与竞争力的公开冲突",
          "summary": "做“AI 风险讨论为何升温”的二创解读（AP，2026-05-21）。https://apnews.com/article/ee318f35acc8a2c43e47f3ebf26cb459",
          "score_total": 19,
          "source_url": ""
        },
        {
          "title": "社区热帖（仅作辅助素材）",
          "summary": "r/technology 对 SpaceX IPO 与算力大单的高互动讨论，用来提炼读者疑问，但事实必须回到权威来源二次核实（Reddit，2026-05-21）。https://www.reddit.com/r/technology/comments/1tj5hbq/spacex_ipo_filing_lays_bare_losses_and_musk/",
          "score_total": 16,
          "source_url": ""
        }
      ]
    },
    {
      "date": "2026-05-20",
      "file": "outputs/daily/2026-05-20-topic-radar.md",
      "top_topics": [
        {
          "title": "选题 A｜Nvidia 业绩 + $80B 回购：AI infra 的“就业温度计”还在升温",
          "score_total": 28,
          "sources": [],
          "source_urls": [],
          "summary": "Nvidia 发布最新季度业绩与指引，并宣布新的 $80B 股票回购授权；媒体解读核心仍是 AI 需求强劲，但也提到中国限制带来的不确定性（背景资料：限制并非当日新推出）。",
          "why_it_matters": "Nvidia 的指引与资本开支链条，往往是“云厂/数据中心/AI infra”招聘景气度的领先指标：只要需求继续上修，相关岗位（云、分布式系统、推理优化、GPU 软件栈、数据中心运维/供应链）更可能出现新增 headcount。 对尚未毕业的学生而言，这类信号能帮助你决定：该把项目/实习经历压在哪条“AI 基建主线”上，而不是只追逐泛 AI 标签。",
          "job_signal": ""
        },
        {
          "title": "选题 B｜量化基金把 GPU 云“买到位”：Lambda × Hudson River Trading 的 AI/算力合作",
          "score_total": 28,
          "sources": [],
          "source_urls": [],
          "summary": "AI/GPU 云厂商 Lambda 宣布与 Hudson River Trading（HRT） 建立新的合作关系，为其提供 AI 计算资源（细节以原文为准）。",
          "why_it_matters": "量化/HFT 的“机会信号”不一定来自公开招聘，而常来自：算力采购、研究基础设施升级、与云/硬件供应商绑定。这往往意味着： 研究团队正在扩容/提效（更需要 ML/系统/数据/平台工程） 或者交易/研究方法在向 AI 进一步渗透（更需要能落地的工程化能力）",
          "job_signal": ""
        },
        {
          "title": "选题 C｜投行自己要 IPO：Lincoln International 上市首日大涨，资本市场窗口在变",
          "score_total": 26,
          "sources": [],
          "source_urls": [],
          "summary": "投资银行 Lincoln International IPO 上市首日股价上涨（具体涨幅以报道为准），释放出：资本市场窗口/投资银行业务的景气度可能在改善。",
          "why_it_matters": "对投行/资本市场相关求职者，IPO 成功与否直接影响： ECM/IB 的 deal flow 预期（从而影响 internship / analyst headcount 与 return offer） 市场对“投行行业复苏”的共识强弱（影响择业与准备节奏）",
          "job_signal": ""
        }
      ],
      "alternatives": [
        {
          "title": "Intuit 宣布裁员约 17%（Reuters/TechCrunch）",
          "summary": "适合写“AI 转型期的避坑与转岗策略”，但不建议写成“行业崩了”。",
          "score_total": 21,
          "source_url": ""
        },
        {
          "title": "NextEra Energy Partners 收购天然气管道公司 Caliber（Reuters）",
          "summary": "数据中心/发电/燃气基础设施与 AI 扩张绑定，适合写“AI 数据中心=电力与管网岗位机会”。",
          "score_total": 22,
          "source_url": ""
        },
        {
          "title": "HSBC CEO 谈 AI 会摧毁也会创造岗位、强调再培训（Reuters）",
          "summary": "可写“金融业 AI 化下的新岗位画像（风控/数据/平台）”，但需要补充更多一手招聘证据（LinkedIn 需二次核实）。",
          "score_total": 20,
          "source_url": ""
        },
        {
          "title": "Hazeltree 披露 4 月 hedge funds 加杠杆、调整对冲（Reuters）",
          "summary": "可写“波动期对冲基金在招什么（风险/系统/执行）”，但信号偏宏观，需要强包装。",
          "score_total": 18,
          "source_url": ""
        },
        {
          "title": "“美股期货上涨，市场等待 Nvidia 财报”（Reuters）",
          "summary": "可作为选题 A 的导语或数据点，不建议单独成稿。",
          "score_total": 15,
          "source_url": ""
        },
        {
          "title": "Reddit：Intuit layoff 高互动讨论贴（r/technology 等）",
          "summary": "可作为“员工视角”素材补充，但需避免把社区观点当事实。",
          "score_total": 16,
          "source_url": ""
        },
        {
          "title": "Reddit：Nvidia earnings thread 高互动讨论（r/wallstreetbets / r/NVDA_Stock）",
          "summary": "适合作为“情绪温度计”和读者互动引导（投票/提问），不宜替代权威来源。",
          "score_total": 17,
          "source_url": ""
        }
      ]
    },
    {
      "date": "2026-05-19",
      "file": "outputs/daily/2026-05-19-topic-radar.md",
      "top_topics": [
        {
          "title": "选题 1：Google × Blackstone 造“独立 TPU 云公司”——AI Infra 从“技术战”变“资本战”，对留学生意味着什么？",
          "score_total": 27,
          "sources": [],
          "source_urls": [],
          "summary": "Google 与 Blackstone 宣布成立 AI 云业务合资公司/新公司，核心卖点是 基于 Google TPU 的算力服务。 公开信息提到 Blackstone 先投 约 50 亿美元股权，目标在 2027 年带来约 500MW 计算/数据中心容量，并计划继续扩张。（需要二次核实：最终结构、容量口径、所在地与交付节奏）",
          "why_it_matters": "你可以把它理解为：AI 竞争的“瓶颈”正在从模型能力，转到算力、机房、电力、网络与资本结构。这会改变未来 1-2 年的招聘重心：更偏 AI infra / cloud / systems / data center / 网络 / 电力与散热，以及“懂技术的金融/战略/BD”岗位。 对尚未毕业的学生尤其关键：大厂/巨头更愿意把预算砸在 CapEx 和 infra 上，但同时会更苛刻地要求“能落地、能节省成本、能上生产”的能力组合。",
          "job_signal": ""
        },
        {
          "title": "选题 2：Meta 5/20 启动新一轮裁员+“AI Pod 化”改组织——你该怎么把自己写成“不会被 AI 取代的那类新人”？",
          "score_total": 27,
          "sources": [],
          "source_urls": [],
          "summary": "多家媒体在 5/19 转述：Meta 计划在 5/20 进行约 10% 裁员，并伴随更大范围的组织调整，强调“围绕 AI workflow/AI agent 重新设计组织”，把部分员工转去 AI 相关新项目、压扁管理层、并披露 关闭一批 open roles（报道提到 6000）。（需要二次核实：最终裁员比例、涉及团队、open roles 口径）",
          "why_it_matters": "“大厂裁员”本身不是新闻点，真正对学生有用的是：大厂正在把‘工作流’变成 AI 可自动化的对象。 这会直接改变 entry-level 的竞争方式：你不仅要会写代码/做分析，更要能证明你能 搭建系统、驱动指标、把 AI 工具嵌入流程并产出稳定结果。 同时也提示求职风险：offer → headcount 冻结/关闭 open role 的概率上升，学生必须把“备选公司与身份路径”放进策略里。",
          "job_signal": ""
        },
        {
          "title": "选题 3：AI 数据中心“模块化工厂化”加速——Armada 融资 2.3 亿美元、在亚利桑那建厂（直说：这类公司更可能给新人机会）",
          "score_total": 27,
          "sources": [],
          "source_urls": [],
          "summary": "Armada 宣布 超额认购的 B 轮融资 2.3 亿美元（披露估值口径为 pre-money 20 亿美元），并与 Johnson Controls 达成框架协议，计划在 亚利桑那建设模块化数据中心生产工厂。 报道提到该工厂项目预计带来 约 500 个直接岗位，以及供应链带动岗位。（需要二次核实：岗位结构、招聘节奏、是否面向应届/实习）",
          "why_it_matters": "对学生而言，这类“AI 基建供应链公司/数据中心产业链公司”往往比巨头更可能给新人 更快的 ownership 与更明确的业务增长叙事（融资 + 建厂 + 交付）。 同时它把“AI infra”从纯软件拉回到“软硬结合”：电力、制冷、机械、可靠性、供应链、工厂运营——非传统 CS 背景也可能切入。",
          "job_signal": ""
        }
      ],
      "alternatives": []
    }
  ]
};
