// Auto-generated by scripts/build-dashboard.py
const CACHE_NAME = "topic-radar-20260905T170520886281Z";
const OFFLINE_PAGE = "./index.html";
const PRECACHE = [OFFLINE_PAGE, "./data.js"];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys
          .filter((key) => key.startsWith("topic-radar-") && key !== CACHE_NAME)
          .map((key) => caches.delete(key))
      ))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  if (event.request.mode !== "navigate") return;

  event.respondWith(
    fetch(event.request)
      .then((response) => {
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        const copy = response.clone();
        event.waitUntil(
          caches.open(CACHE_NAME).then((cache) => cache.put(OFFLINE_PAGE, copy))
        );
        return response;
      })
      .catch(() => caches.match(OFFLINE_PAGE))
  );
});
